/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.views;

import biblioteca.controllers.ControladorPrincipal;

/**
 *
 * @author Rodri
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private ControladorPrincipal ctrlPrincipal;
    
    TelaDevolucao tD = new TelaDevolucao(ctrlPrincipal);
    TelaEmprestimo tE = new TelaEmprestimo(ctrlPrincipal);
    TelaUsuario tU = new TelaUsuario(ctrlPrincipal);
    TelaLivro tL = new TelaLivro(ctrlPrincipal);
    

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        this.ctrlPrincipal = new ControladorPrincipal();
        tD.setVisible(false);
        tE.setVisible(false);
        tL.setVisible(false);
        tU.setVisible(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoEfetuarEmprestimo = new javax.swing.JButton();
        botaoEfetuarDevolucao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botaoCadastrarLivros = new javax.swing.JButton();
        botaoCadastrarUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");
        setBackground(new java.awt.Color(255, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        botaoEfetuarEmprestimo.setText("Efetuar Emprestimo");
        botaoEfetuarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEfetuarEmprestimoActionPerformed(evt);
            }
        });

        botaoEfetuarDevolucao.setText("Efetuar Devolução");
        botaoEfetuarDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEfetuarDevolucaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tela Principal");
        jLabel1.setToolTipText("");

        botaoCadastrarLivros.setText("Cadastrar Livros");
        botaoCadastrarLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarLivrosActionPerformed(evt);
            }
        });

        botaoCadastrarUsuarios.setText("Cadastrar Usuarios");
        botaoCadastrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoCadastrarLivros)
                        .addGap(18, 18, 18)
                        .addComponent(botaoCadastrarUsuarios)
                        .addGap(18, 18, 18)
                        .addComponent(botaoEfetuarEmprestimo)
                        .addGap(18, 18, 18)
                        .addComponent(botaoEfetuarDevolucao)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastrarLivros)
                    .addComponent(botaoCadastrarUsuarios)
                    .addComponent(botaoEfetuarEmprestimo)
                    .addComponent(botaoEfetuarDevolucao))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarLivrosActionPerformed
        tL.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarLivrosActionPerformed

    private void botaoCadastrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarUsuariosActionPerformed
        tU.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarUsuariosActionPerformed

    private void botaoEfetuarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEfetuarEmprestimoActionPerformed
        tE.setVisible(true);
    }//GEN-LAST:event_botaoEfetuarEmprestimoActionPerformed

    private void botaoEfetuarDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEfetuarDevolucaoActionPerformed
        tD.setVisible(true);
    }//GEN-LAST:event_botaoEfetuarDevolucaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrarLivros;
    private javax.swing.JButton botaoCadastrarUsuarios;
    private javax.swing.JButton botaoEfetuarDevolucao;
    private javax.swing.JButton botaoEfetuarEmprestimo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
