/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.views;

import biblioteca.controllers.ControladorPrincipal;
import biblioteca.entitys.Livro;
import biblioteca.entitys.Usuario;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rodri
 */
public class TelaEmprestimo extends javax.swing.JFrame {

    private ControladorPrincipal ctrlPrincipal;
    
    /**
     * Creates new form TelaEmprestimo
     * @param ctrlPrincipal
     */
    public TelaEmprestimo(ControladorPrincipal ctrlPrincipal) {
        initComponents();
        this.ctrlPrincipal = ctrlPrincipal;
    }

    public ControladorPrincipal getCtrlPrincipal() {
        return ctrlPrincipal;
    }

    public void setCtrlPrincipal(ControladorPrincipal ctrlPrincipal) {
        this.ctrlPrincipal = ctrlPrincipal;
    }
    
    private void setarTempoLimparFormulario(){
        try {
            TimeUnit.SECONDS.sleep(3);
        } catch (InterruptedException ex) {
            Logger.getLogger(TelaEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        campoCodigoLivro.setText("");
        campoCodigoUsuario.setText("");
        telaEmprestimoMensagem.setText("");
        
        this.setVisible(false);
    }
    
    private void limparFormulario(){
        campoCodigoLivro.setText("");
        campoCodigoUsuario.setText("");
        telaEmprestimoMensagem.setText("");
        
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        telaEmprestimoTitulo = new javax.swing.JLabel();
        telaEmpretimoCodigoUsuario = new javax.swing.JLabel();
        campoCodigoUsuario = new javax.swing.JTextField();
        telaEmprestimoCodigoLivro = new javax.swing.JLabel();
        campoCodigoLivro = new javax.swing.JTextField();
        telaEmprestimoDataEmprestimo = new javax.swing.JLabel();
        botaoCadastrar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        calandarioTelaEmprestimo = new com.michaelbaranov.microba.calendar.CalendarPane();
        telaEmprestimoMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        telaEmprestimoTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        telaEmprestimoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        telaEmprestimoTitulo.setText("Tela Emprestimo");

        telaEmpretimoCodigoUsuario.setText("Código Usuário:");

        campoCodigoUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        telaEmprestimoCodigoLivro.setText("Código Livro:");

        campoCodigoLivro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        telaEmprestimoDataEmprestimo.setText("Data Emprestimo: ");

        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(telaEmpretimoCodigoUsuario)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(telaEmprestimoCodigoLivro)
                        .addGap(31, 31, 31)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(campoCodigoLivro)
                    .addComponent(campoCodigoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(telaEmprestimoDataEmprestimo)
                .addGap(18, 18, 18)
                .addComponent(calandarioTelaEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaEmprestimoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(telaEmprestimoMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(botaoCancelar)
                        .addGap(67, 67, 67)
                        .addComponent(botaoCadastrar)))
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(telaEmprestimoTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telaEmpretimoCodigoUsuario)
                            .addComponent(campoCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telaEmprestimoDataEmprestimo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telaEmprestimoCodigoLivro)
                            .addComponent(campoCodigoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(calandarioTelaEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastrar)
                    .addComponent(botaoCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telaEmprestimoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        limparFormulario();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        int codigoLivro = Integer.parseInt(this.campoCodigoLivro.getText());
        int codigoUsuario = Integer.parseInt(this.campoCodigoUsuario.getText());
        Date dataEmprestimo = this.calandarioTelaEmprestimo.getDate();
        
        Livro livro = new Livro();
        livro.setCodigo(codigoLivro);
        livro = this.ctrlPrincipal.getCtrlLivro().find(livro);
        
        Usuario usuario = new Usuario();
        usuario.setCodigo(codigoUsuario);
        usuario = this.ctrlPrincipal.getCtrlUsuario().find(usuario);
        
        if(livro != null && usuario != null){ 
            String mensagem = this.ctrlPrincipal.getCtrlEmprestimo().emprestar(livro, usuario, dataEmprestimo);
            telaEmprestimoMensagem.setText(mensagem);
            setarTempoLimparFormulario();
        } else {
            telaEmprestimoMensagem.setText("Não foi possivel realizar o emprestimo!");
            setarTempoLimparFormulario();
        }
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoCancelar;
    private com.michaelbaranov.microba.calendar.CalendarPane calandarioTelaEmprestimo;
    private javax.swing.JTextField campoCodigoLivro;
    private javax.swing.JTextField campoCodigoUsuario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel telaEmprestimoCodigoLivro;
    private javax.swing.JLabel telaEmprestimoDataEmprestimo;
    private javax.swing.JLabel telaEmprestimoMensagem;
    private javax.swing.JLabel telaEmprestimoTitulo;
    private javax.swing.JLabel telaEmpretimoCodigoUsuario;
    // End of variables declaration//GEN-END:variables
}
