/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.views;

import biblioteca.controllers.ControladorPrincipal;
import biblioteca.entitys.Livro;
import biblioteca.entitys.Usuario;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rodri
 */
public class TelaDevolucao extends javax.swing.JFrame {

    private ControladorPrincipal ctrlPrincipal;
    
    /**
     * Creates new form TelaDevolucao
     * @param controladorPrincipal
     */
    public TelaDevolucao(ControladorPrincipal controladorPrincipal) {
        initComponents();
        ctrlPrincipal = controladorPrincipal;
    }

    public ControladorPrincipal getCtrlPrincipal() {
        return ctrlPrincipal;
    }

    public void setCtrlPrincipal(ControladorPrincipal ctrlPrincipal) {
        this.ctrlPrincipal = ctrlPrincipal;
    }
    
    private void setarTempoLimparFormulario(){
        try {
            TimeUnit.SECONDS.sleep(3);
        } catch (InterruptedException ex) {
            Logger.getLogger(TelaEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        campoCodigoLivro.setText("");
        campoCodigoUsuario.setText("");
        telaDevolucaoMensagem.setText("");
        
        this.setVisible(false);
    }
    
    private void limparFormulario(){
        campoCodigoLivro.setText("");
        campoCodigoUsuario.setText("");
        telaDevolucaoMensagem.setText("");
        
        this.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        telaDevolucaoTItulo = new javax.swing.JLabel();
        campoCodigoLivro = new javax.swing.JTextField();
        telaDevolucaoDataEmprestimo = new javax.swing.JLabel();
        telaDevolucaoCodigoUsuario = new javax.swing.JLabel();
        campoCodigoUsuario = new javax.swing.JTextField();
        telaDevolucaoCodigoLivro = new javax.swing.JLabel();
        botaoCancelar = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        calandarioTelaEmprestimo = new com.michaelbaranov.microba.calendar.CalendarPane();
        telaDevolucaoMensagem = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        telaDevolucaoTItulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        telaDevolucaoTItulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        telaDevolucaoTItulo.setText("Tela Devolução");

        telaDevolucaoDataEmprestimo.setText("Data Emprestimo:");

        telaDevolucaoCodigoUsuario.setText("Código Usuário:");

        campoCodigoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoUsuarioActionPerformed(evt);
            }
        });

        telaDevolucaoCodigoLivro.setText("Código Livro:");

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(telaDevolucaoCodigoUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(campoCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(telaDevolucaoCodigoLivro)
                        .addGap(18, 18, 18)
                        .addComponent(campoCodigoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(telaDevolucaoDataEmprestimo)
                .addGap(18, 18, 18)
                .addComponent(calandarioTelaEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaDevolucaoTItulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(telaDevolucaoMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoCancelar)
                        .addGap(66, 66, 66)
                        .addComponent(botaoCadastrar)))
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaDevolucaoTItulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(calandarioTelaEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(telaDevolucaoCodigoUsuario)
                                .addComponent(campoCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(telaDevolucaoDataEmprestimo))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telaDevolucaoCodigoLivro)
                            .addComponent(campoCodigoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelar)
                    .addComponent(botaoCadastrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telaDevolucaoMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCodigoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoUsuarioActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        int codigoLivro = Integer.parseInt(this.campoCodigoLivro.getText());
        int codigoUsuario = Integer.parseInt(this.campoCodigoUsuario.getText());
        Date dataEmprestimo = this.calandarioTelaEmprestimo.getDate();
        
        Livro livro = new Livro();
        livro.setCodigo(codigoLivro);
        livro = this.ctrlPrincipal.getCtrlLivro().find(livro);
        
        Usuario usuario = new Usuario();
        usuario.setCodigo(codigoUsuario);
        usuario = this.ctrlPrincipal.getCtrlUsuario().find(usuario);
        
        if(livro != null && usuario != null){ 
            String mensagem = "";//this.ctrlPrincipal.getCtrlEmprestimo().devolver()
            telaDevolucaoMensagem.setText(mensagem);
            setarTempoLimparFormulario();
        } else {
            telaDevolucaoMensagem.setText("Não foi possivel realizar a devolução!");
            setarTempoLimparFormulario();
        }
    }//GEN-LAST:event_botaoCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoCancelar;
    private com.michaelbaranov.microba.calendar.CalendarPane calandarioTelaEmprestimo;
    private javax.swing.JTextField campoCodigoLivro;
    private javax.swing.JTextField campoCodigoUsuario;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel telaDevolucaoCodigoLivro;
    private javax.swing.JLabel telaDevolucaoCodigoUsuario;
    private javax.swing.JLabel telaDevolucaoDataEmprestimo;
    private javax.swing.JLabel telaDevolucaoMensagem;
    private javax.swing.JLabel telaDevolucaoTItulo;
    // End of variables declaration//GEN-END:variables
}
