/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author rodrigo
 */
public class calc extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer calc
     */
    public calc() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoInputDados = new javax.swing.JTextField();
        campoResposta = new javax.swing.JTextField();
        botaoDigito7 = new javax.swing.JButton();
        botaoDigito8 = new javax.swing.JButton();
        botaoDigito9 = new javax.swing.JButton();
        botaoDigitoDivide = new javax.swing.JButton();
        botaoDigito4 = new javax.swing.JButton();
        botaoDigito6 = new javax.swing.JButton();
        botaoDigito5 = new javax.swing.JButton();
        botaoDigitoMultiplicacao = new javax.swing.JButton();
        botaoDigito3 = new javax.swing.JButton();
        botaoDigito2 = new javax.swing.JButton();
        botaoDigito1 = new javax.swing.JButton();
        botaoDigito0 = new javax.swing.JButton();
        botaoDigitoSeparador = new javax.swing.JButton();
        botaoDigitoIgual = new javax.swing.JButton();
        botaoDigitoDiminui = new javax.swing.JButton();
        botaoDigitoSoma = new javax.swing.JButton();

        botaoDigito7.setText("7");

        botaoDigito8.setText("8");

        botaoDigito9.setText("9");

        botaoDigitoDivide.setText("/");

        botaoDigito4.setText("4");

        botaoDigito6.setText("6");

        botaoDigito5.setText("5");

        botaoDigitoMultiplicacao.setText("*");

        botaoDigito3.setText("3");

        botaoDigito2.setText("2");

        botaoDigito1.setText("1");

        botaoDigito0.setText("0");

        botaoDigitoSeparador.setText(".");

        botaoDigitoIgual.setText("=");

        botaoDigitoDiminui.setText("-");

        botaoDigitoSoma.setText("+");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(campoResposta)
            .addComponent(campoInputDados)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoDigito1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(botaoDigito0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoDigitoSeparador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoDigito2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoDigitoIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoDigito3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoDigito4, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(botaoDigito7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoDigito5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoDigito6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoDigito8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoDigito9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoDigitoMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoDigitoDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoDigitoDiminui, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoDigitoSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(campoInputDados, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(campoResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoDigito7)
                    .addComponent(botaoDigito8)
                    .addComponent(botaoDigito9)
                    .addComponent(botaoDigitoDivide))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoDigitoMultiplicacao)
                    .addComponent(botaoDigito6)
                    .addComponent(botaoDigito5)
                    .addComponent(botaoDigito4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoDigito2)
                    .addComponent(botaoDigito3)
                    .addComponent(botaoDigito1)
                    .addComponent(botaoDigitoDiminui))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoDigitoIgual)
                    .addComponent(botaoDigitoSeparador)
                    .addComponent(botaoDigito0)
                    .addComponent(botaoDigitoSoma))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDigito0;
    private javax.swing.JButton botaoDigito1;
    private javax.swing.JButton botaoDigito2;
    private javax.swing.JButton botaoDigito3;
    private javax.swing.JButton botaoDigito4;
    private javax.swing.JButton botaoDigito5;
    private javax.swing.JButton botaoDigito6;
    private javax.swing.JButton botaoDigito7;
    private javax.swing.JButton botaoDigito8;
    private javax.swing.JButton botaoDigito9;
    private javax.swing.JButton botaoDigitoDiminui;
    private javax.swing.JButton botaoDigitoDivide;
    private javax.swing.JButton botaoDigitoIgual;
    private javax.swing.JButton botaoDigitoMultiplicacao;
    private javax.swing.JButton botaoDigitoSeparador;
    private javax.swing.JButton botaoDigitoSoma;
    private javax.swing.JTextField campoInputDados;
    private javax.swing.JTextField campoResposta;
    // End of variables declaration//GEN-END:variables
}
